# Generated by Django 3.2.15 on 2023-02-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='carburante',
            field=models.CharField(blank=True, choices=[('AV', 'Autovettura'), ('MV', 'Motovettura')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='auto',
            name='cilindrata',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cilindrata'),
        ),
        migrations.AddField(
            model_name='auto',
            name='data_immatricolazione',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auto',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='auto',
            name='potenza',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Potenza in kW o CV'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modello Auto'),
        ),
    ]
