# Generated by Django 3.2.15 on 2023-02-16 13:57

import core.auto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_auto_20230215_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='carburante',
            field=models.CharField(blank=True, choices=[('AV', 'Autovettura'), ('MV', 'Motovettura'), ('CM', 'Ciclomotore')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='auto',
            name='tipo',
            field=models.CharField(choices=[('AV', 'Autovettura'), ('MV', 'Motovettura'), ('CM', 'Ciclomotore')], default='AV', max_length=2),
        ),
        migrations.AlterField(
            model_name='documentoauto',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.auto.models.documento_auto_file_path, verbose_name='File Documento'),
        ),
        migrations.AlterField(
            model_name='documentoauto',
            name='numero',
            field=models.CharField(blank=True, help_text='se assente verrà auto assegnato', max_length=100, null=True, verbose_name='Numero'),
        ),
    ]
