# Generated by Django 4.0.10 on 2023-02-26 21:16

import core.auto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_auto_20230216_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='carburante',
            field=models.CharField(blank=True, choices=[('', 'Scelta Carbrante'), ('BE', 'Benzina'), ('DI', 'Diesel'), ('IB', 'Ibrida'), ('EL', 'Elettrica')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='auto',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.auto.models.auto_file_path, verbose_name='File Auto'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='image_main',
            field=models.ImageField(blank=True, null=True, upload_to=core.auto.models.auto_file_path, verbose_name='Immagine Auto'),
        ),
        migrations.AlterField(
            model_name='documentoauto',
            name='controllo_scadenza',
            field=models.BooleanField(default=True, help_text='check per non controllare questo documento', verbose_name='Controlo Scadenza'),
        ),
        migrations.AlterField(
            model_name='documentoauto',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.auto.models.documento_auto_file_path, verbose_name='Allegato al Documento'),
        ),
        migrations.AlterField(
            model_name='documentoauto',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome Documento'),
        ),
        migrations.AlterField(
            model_name='documentoauto',
            name='numero',
            field=models.CharField(blank=True, help_text='se assente verrà auto assegnato', max_length=100, null=True, verbose_name='Numero Documento'),
        ),
    ]
