# Generated by Django 3.2.15 on 2023-02-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documenti_user', verbose_name='File'),
        ),
    ]
